CREATE DATABASE CAFE_NOIR_DB
USE CAFE_NOIR_DB

ALTER TABLE fact 
ALTER COLUMN Profit INT;

SELECT * FROM fact
SELECT * FROM Location
SELECT * FROM Product

--1. Display the number of states present in the Location Table. 
SELECT COUNT(DISTINCT(State)) as Total_States FROM Location

--2. How many products are of regular type?
SELECT COUNT(Product) as Product_Regular
FROM Product
WHERE Type='Regular';  

--3. How much spending has been done on marketing of product ID 1?
SELECT ProductId,SUM(Marketing) as Total_Spendings FROM fact
WHERE ProductId = 1
GROUP BY ProductId;

--4. What is the minimum sales of a product? 
SELECT ProductId, Sales
FROM fact
WHERE Sales=(
	  SELECT MIN(Sales)
	  FROM fact 
	  WHERE Sales IS NOT NULL
);

--5. Display the max Cost of Good Sold (COGS).
SELECT DISTINCT ProductId, COGS as MAX_COGS
FROM fact
WHERE COGS= (
	SELECT MAX(COGS)
	FROM fact
	WHERE COGS IS NOT NULL
	);
			

--6. Display the details of the product where product type is coffee. 
SELECT Product, Product_Type
FROM Product
WHERE Product_Type= 'Coffee'

--7. Display the details where total expenses are greater than 40. 

SELECT * FROM dbo.fact 
WHERE Total_Expenses > 40;

--8. What is the average sales in area code 719? 

SELECT AVG(Sales) as Average_Sales, Area_Code
FROM dbo.fact
WHERE Area_Code = 719
GROUP BY Area_Code;

--9. Find out the total profit generated by Colorado state.

-- Area_Code as Primary Key 
Select Count(DISTINCT(Area_Code)) as Union_Area_Code from fact

-- Check duplicates
SELECT Area_Code, COUNT(*)
FROM dbo.fact
GROUP BY Area_Code
HAVING COUNT(*) > 1
ORDER BY Area_Code;

-- Check NULLs
SELECT *
FROM dbo.fact
WHERE Area_Code IS NULL;

SELECT SUM(f.Budget_Profit) AS Total_Profit
FROM fact f
JOIN Location l ON f.Area_Code=l.Area_Code 
WHERE State= 'Colorado'

--10. Display the average inventory for each product ID.

SELECT Productid, AVG(Inventory) as Average_Inventary FROM fact
GROUP BY ProductId
Order By ProductId

--11. Display state in a sequential order in a Location Table.

SELECT State FROM Location
GROUP BY State

--12. Display the average budget of the Product where the average budget margin should be greater than 100.

SELECT p.Product,AVG(f.Budget_Margin) as Average_Budget_Margin
FROM fact f
JOIN Product p ON f.ProductId=p.ProductId
GROUP BY p.Product
HAVING AVG(f.Budget_Margin) > 100;

--13. What is the total sales done on date 2010-01-01? 

SELECT Date,SUM(Sales) as Total_Sales FROM fact
WHERE Date='2010-01-01'
GROUP BY Date

--14. Display the average total expense of each product ID on an individual date. 

SELECT f.ProductId,f.Date ,AVG(f.Total_Expenses) AS Average_Total_Expense
FROM fact f
GROUP BY f.ProductId,f.Date 
ORDER BY f.ProductId,f.Date

--15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code. 

SELECT TOP 10
    f.Date,
    f.ProductId,
    p.Product_Type,
    p.Product,
    f.Sales,
    f.Profit,
    l.State,
    l.Area_Code
FROM fact f
JOIN Product p 
    ON f.ProductId = p.ProductId
JOIN Location l 
    ON f.Area_Code = l.Area_Code
GROUP BY 
    f.Date,
    f.ProductId,
    p.Product_Type,
    p.Product,
    f.Sales,
    f.Profit,
    l.State,
    l.Area_Code

--16. Display the rank without any gap to show the sales wise rank. 

SELECT Sales, DENSE_RANK() OVER (ORDER BY Sales DESC) as Sales_Rank
FROM fact ;

--17. Find the state wise profit and sales.

SELECT l.State,SUM(f.Profit) as Total_Profit,SUM(f.Sales) as Total_Sales
FROM fact f
JOIN Location l ON f.Area_Code=l.Area_Code
GROUP BY l.State

--18. Find the state wise profit and sales along with the product name. 

SELECT p.Product,l.State, SUM(f.Profit) as Total_Profit, SUM(f.Sales) as Total_Sales
FROM fact f
JOIN Location l ON f.Area_Code=l.Area_Code
JOIN Product p ON f.ProductId=p.ProductId
GROUP BY p.Product,l.State


--19. If there is an increase in sales of 5%, calculate the increased sales

SELECT Sales,Sales * 1.05 as Increased_Sales 
FROM fact

--20. Find the maximum profit along with the product ID and product type. 

SELECT MAX(f.Profit) as Maximum_Profit,p.ProductId,p.Product_Type
FROM fact f
JOIN Product p
ON f.ProductId=p.ProductId
GROUP BY p.ProductId,p.Product_Type  
ORDER BY MAX(f.Profit) DESC

--21. Create a stored procedure to fetch the result according to the product type from Product Table. 

CREATE PROCEDURE Get_Product_type
	@product_type NVARCHAR(50)
AS
BEGIN
	SELECT * FROM Product
	WHERE Product_Type=@product_type;
END;

EXEC Get_Product_type @product_type= 'Coffee'

--22. Write a query by creating a condition in which if the total expenses is less than 60 then it is a profit or else loss. 

SELECT Total_Expenses,
	CASE 
		WHEN Total_Expenses < 60 THEN 'PROFIT'
		ELSE 'LOSS'
	END AS STATUS
FROM fact;

--23. Give the total weekly sales value with the date and product IDdetails. Useroll-up to pull the data in hierarchical order.
SELECT 
	Date,
	ProductId,
	SUM(Sales) AS Total_Weekly_Sales
FROM fact
GROUP BY ROLLUP (Date,ProductId)
ORDER BY Date,ProductId

--24. Apply union and intersection operator on the tables which consist of attribute area code. 
SELECT Area_Code FROM fact
UNION
SELECT Area_Code FROM Location
ORDER BY Area_Code

SELECT Area_Code FROM fact
INTERSECT
SELECT Area_Code FROM Location
ORDER By Area_Code

--25. Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference.

CREATE FUNCTION dbo.GetbyProductType
	(
		@Producttype NVARCHAR(50)
	)
	RETURNS TABLE
	AS 
	RETURN 
	(
		SELECT ProductId,Product,Product_Type,Type
		FROM Product
		WHERE Product_Type=@Producttype
	)

SELECT * FROM dbo.GetbyProductType('Coffee')

--26. Change the product type from coffee to tea where product ID is 1 and undo it.

BEGIN TRANSACTION;
UPDATE Product
SET Product_Type='Tea'
WHERE ProductId=1;

SELECT * FROM Product WHERE ProductId=1;

ROLLBACK;

SELECT * FROM Product WHERE ProductId=1;


--27. Display the date, product ID and sales where total expenses are between 100 to 200. 

SELECT Date,ProductId,Sales,Total_Expenses
FROM fact
WHERE Total_Expenses Between 100 AND 200

-----------------------------------------------------------------------------------------------

SELECT ProductId,SUM(Sales) AS Total_Sales,SUM(Total_Expenses) AS Total_Expenses
FROM fact
WHERE Total_Expenses Between 100 AND 200
GROUP BY ProductId

--28. Delete the records in the Product Table for regular type.

BEGIN TRANSACTION
DELETE FROM Product
WHERE Type='Regular'
SELECT * FROM Product

ROLLBACK;

SELECT * FROM Product

--29. Display the ASCII value of the fifth character from the column Product.

SELECT ProductId, Product, ASCII(SUBSTRING(Product,5,1)) As Fifthchar
FROM Product
